---
- hosts: "iosdevices"
  connection: network_cli
  gather_facts: no

  tasks:
   - name: run show version on remote devices
     cisco.ios.ios_command:
      commands: show running-config 

   - name: Play 2 Write config to file
     copy:
       content: "{{ cli_result_config.stdout[0] }}\n"
       dest: "~/aflab-network/backups/{{hostvars.localhost.DTG}}/{{inventory_hostname}}.cfg"
...
