---
## Playbook to get system time and append it to backup files
- name: Create local folders for IOS device backups
  hosts: localhost

  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars.localhost.DTG}}
     file:
      path: ~/aflab-network/backups/{{hostvars.localhost.DTG}}
      state: directory
  run_once: true
...
